version: '3'
services:
  cdk:
    build:
      args:
        - APP_UID=${CDK_UID}
        - APP_GID=${CDK_GID}
        - APP_USER=${CDK_USER}
        - APP_GROUP=${CDK_GROUP}
        - APP_HOME=${HOME}
        - DOCKER_GID=${DOCKER_GID}
        - DOCKER_GROUP=${DOCKER_GROUP}
      context: docker/cdk
    container_name: cdk
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - GIT_COMMITTER_NAME=${GIT_USER_NAME}
      - GIT_COMMITTER_EMAIL=${GIT_USER_EMAIL}
      - GIT_AUTHOR_NAME=${GIT_USER_NAME}
      - GIT_AUTHOR_EMAIL=${GIT_USER_EMAIL}
    network_mode: host
    tty: true
    user: ${CDK_UID}:${DOCKER_GID}
    volumes:
      - ./docker/cdk/.vscode-server:${HOME}/.vscode-server
      - ${PWD}:${PWD}
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: ${PWD}/cdk
